### 1. 로그인
POST http://localhost/login
Content-Type: application/json

{"id": "admin", "pw": "pass"}

### 2. 로그인 인증(토큰 인증)
POST http://localhost/check
Content-Type: application/jㄴson
Authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImFkbWluIiwicHciOiJwYXNzIiwiaWF0IjoxNzg3ODk5MzQwLCJleHAiOjE3ODc5MDExNDB9.z9KqYopXCeuRW7Pf1gPpfRtkFeY1UWxpePDkmhTOVTs